import re

"""
    Bytecode is an intermediary language. It's the output generated by languages,
    which will be later interpreted by an interpreter. The Java bytecode that is interpreted by JVM
    is probably the best known example.
"""

pattern = re.compile(r'\bfoo\b')
res = pattern.match("foo bar")
print(res)
